const BUTTON_TYPES = ['default', 'outline', 'text'];
const COMPONENT_STATES = ['default', 'disabled', 'error'];
const COLORS = [
  'primary',
  'secondary',
  'black',
  'blue',
  'gray',
  'green',
  'orange',
  'purple',
  'red',
  'white',
];
const PRODUCT_ICONS = [
  'college',
  'military',
  'workforce',
  'career-interests',
  'location',
  'organizations-clubs',
  'arts-crafts',
  'sports-exercise',
  'volunteer',
  'cooking-baking',
  'music',
  'certification',
  'desk',
  'outdoor',
  'private-office',
  'open-office',
  'indoor',
  'manufacturing',
  'remote',
  'travel',
  'colleges',
  'demographics',
  'profile',
  'career-interests',
];
const SECONDARY_ICONS = ['pdf', 'doc', 'video', 'image', 'play'];
const SIZES = ['small', 'large', 'jumbo'];
const SYSTEM_ICONS = [
  'share',
  'preview',
  'export',
  'follow',
  'message',
  'badges',
  'website',
  'edit',
  'clear',
  'navigate',
  'down',
  'up',
  'user',
  'visibility',
  'help',
  'close',
  'calendar',
  'warning',
  'add',
  'filter',
  'menu',
  'search',
  'tutorial',
  'yes',
  'no',
  'hobby',
  'interest',
  'outdoor',
  'indoor',
  'popular',
];

export {
  BUTTON_TYPES,
  COMPONENT_STATES,
  COLORS,
  PRODUCT_ICONS,
  SECONDARY_ICONS,
  SIZES,
  SYSTEM_ICONS,
};
